title: Wind In My Hair 
description: A blog by Megha 

url: http://windinmyhair.in
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: dsmegha
   twitter: dsmegha
   facebook: dsmegha
   email: dsmegha@gmail.com

google_analytics: "UA-58263416-1"

